// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygexvvcsxenrnidqtsgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZXh2dmNzeGVucm5pZHF0c2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODY1NDgsImV4cCI6MjA3NDY2MjU0OH0.8UWke0lAqNQWj2YUPyDEp4qBxRS0Mdj07srcvCIEqAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});